@echo off
echo Activating virtual environment...
call venv_ayu1.5\Scripts\activate
echo Installing dependencies...
pip install python-dotenv streamlit
echo Starting application...
python run_app.py
pause